### PR TITLE
removed a duplicate speaker Praveen

### PR DESCRIPTION
**Pull request by daminisatya**

### CODE REVIEW

**Comment by daminisatya** [comment]
@jig08 There is another one. Let me update it :)

**Comment by daminisatya** [comment]
@jig08 Done adding the changes

**Comment by jigyasa-grover** [comment]
Thanks. Here you go.

**Comment by joerx** [comment]
Please do not edit the JSON files directly - they are auto-generated by the scraper and will be replaced every time we updated the schedule. Instead, try to find the underlying problem in the scraper code. See #10 for a good example.

**Pull request merged**
